In [1]:
# how to concatenate two tuples

In [4]:
a = (1,2,"a")
b = (5,3,4)
print(a + b)


(1, 2, 'a', 5, 3, 4)


In [5]:
print(b+a)

(5, 3, 4, 1, 2, 'a')


In [6]:
# how can u initialize 5x5 numpy array with only zeros 

In [7]:
import numpy as np
n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
n = np.ones((5,5))
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
n = np.twoes((5,5))
print(n)

AttributeError: module 'numpy' has no attribute 'twoes'

In [12]:
import pandas as pd

list_data = [1,2,3,4,'a','b','c',5,6,7,8]
series = pd.Series(list_data)
print(series)

0     1
1     2
2     3
3     4
4     a
5     b
6     c
7     5
8     6
9     7
10    8
dtype: object


In [13]:
# what is the use of grtoupby function in pandas


In [14]:
df = pd.DataFrame({"Vehicle":["Ford","Tata","Bajaj","Yamaha"],"Type":["Car","Car","Bike","Bike"]})

In [15]:
df

Vehicle  Type
0    Ford   Car
1    Tata   Car
2   Bajaj  Bike
3  Yamaha  Bike

In [16]:
df.groupby("Type").count()

Vehicle
Type         
Bike        2
Car         2

In [18]:
# How to create DataFrame from lists

In [20]:
bikes = ["Bajaj","Yamaha","Honda","Hero"]
cars = ["Ford","Tata","Maruti","Hyundai"]

df = pd.DataFrame()

df["Cars"] = cars
df["Bikes"] = bikes
print(df)

      Cars   Bikes
0     Ford   Bajaj
1     Tata  Yamaha
2   Maruti   Honda
3  Hyundai    Hero


In [23]:
bikes = ["Bajaj","Yamaha","Honda","Hero","Kawasaki","BMW","TVS"]
cars = ["Ford","Tata","Maruti","Hyundai","Lamborghini","Masserati","Ferrari"]

dict = {"Cars":cars,"Bikes":bikes}

df = pd.DataFrame(dict)
print(df)

          Cars     Bikes
0         Ford     Bajaj
1         Tata    Yamaha
2       Maruti     Honda
3      Hyundai      Hero
4  Lamborghini  Kawasaki
5    Masserati       BMW
6      Ferrari       TVS


In [24]:
# how to access first five entries and last five entries of DataFrame

In [25]:
# first five

In [29]:
df = pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\Kaggle data new\gcar_data.csv")

In [30]:
df

Unnamed: 0       brand                 model  color registration_date  \
0           75721        ford             Ford Kuga  black           05/2023   
1           80184     hyundai           Hyundai i10  black           09/2018   
2           19864        audi        Audi Q4 e-tron   grey           05/2021   
3           76699       honda            Honda CR-V    red           07/2018   
4           92991         kia          Kia Sportage  black           02/2023   
...           ...         ...                   ...    ...               ...   
99995        6265        audi               Audi A1   blue           05/2012   
99996       54886        fiat              Fiat 500  black           12/2019   
99997       76820       honda            Honda CR-V  brown           01/2019   
99998         860  alfa-romeo  Alfa Romeo Giulietta   grey           12/2020   
99999       15795        audi               Audi A3  black           05/2018   

       year price_in_euro power_kw power_ps transmission_type fuel_type  \
0      2023         38490      140      190         Automatic    Hybrid   
1      2018         11555       49       67            Manual    Petrol   
2      2021         48886      125      170         Automatic  Electric   
3      2018         24490      114      155         Automatic    Petrol   
4      2023         34990      110      150            Manual    Petrol   
...     ...           ...      ...      ...               ...       ...   
99995  2012         12599       90      122            Manual    Petrol   
99996  2019          9999       51       69         Automatic    Petrol   
99997  2019         24800      127      173            Manual    Petrol   
99998  2020         22990      125      170         Automatic    Diesel   
99999  2018         21900      110      150            Manual    Petrol   

      fuel_consumption_l_100km fuel_consumption_g_km  mileage_in_km  \
0                 5,4 l/100 km              124 g/km          100.0   
1                 4,6 l/100 km              106 g/km        27782.0   
2                          NaN                0 g/km         4247.0   
3                 7,5 l/100 km              175 g/km        57000.0   
4                 5,9 l/100 km              150 g/km         7500.0   
...                        ...                   ...            ...   
99995             5,3 l/100 km              126 g/km       148000.0   
99996             5,2 l/100 km              120 g/km        31698.0   
99997             6,3 l/100 km              143 g/km        77900.0   
99998             5,5 l/100 km              145 g/km        52251.0   
99999             5,3 l/100 km              120 g/km        30400.0   

                                      offer_description  
0        ST-Line Hybrid Adapt.LED+Head-Up-Display Klima  
1                   blue Trend,Viele Extras,Top-Zustand  
2          35 e-tron S line/Matrix/Pano/ACC/SONOS/LM 21  
3                 2.0 Lifestyle Plus Automatik Navi FAP  
4                          1.6 T 48V 2WD Spirit LED, WR  
...                                                 ...  
99995        Ambition TFSI Navi/Leder/SHZ/PTS/KETTE NEU  
99996                       1.2 Lounge +Automatik + PDC  
99997  1.5T 2WD Elegance * 1. Hand * 24 Mon. Garantie *  
99998            Lusso Ti 2.0 JTDM 16V Xenon Leder Navi  
99999         Sportback1.5 Sport|VIRTUAL|NAVI|LED|30KM|  

[100000 rows x 15 columns]

In [31]:
# first five rows
df.head(5)

Unnamed: 0    brand           model  color registration_date  year  \
0       75721     ford       Ford Kuga  black           05/2023  2023   
1       80184  hyundai     Hyundai i10  black           09/2018  2018   
2       19864     audi  Audi Q4 e-tron   grey           05/2021  2021   
3       76699    honda      Honda CR-V    red           07/2018  2018   
4       92991      kia    Kia Sportage  black           02/2023  2023   

  price_in_euro power_kw power_ps transmission_type fuel_type  \
0         38490      140      190         Automatic    Hybrid   
1         11555       49       67            Manual    Petrol   
2         48886      125      170         Automatic  Electric   
3         24490      114      155         Automatic    Petrol   
4         34990      110      150            Manual    Petrol   

  fuel_consumption_l_100km fuel_consumption_g_km  mileage_in_km  \
0             5,4 l/100 km              124 g/km          100.0   
1             4,6 l/100 km              106 g/km        27782.0   
2                      NaN                0 g/km         4247.0   
3             7,5 l/100 km              175 g/km        57000.0   
4             5,9 l/100 km              150 g/km         7500.0   

                                offer_description  
0  ST-Line Hybrid Adapt.LED+Head-Up-Display Klima  
1             blue Trend,Viele Extras,Top-Zustand  
2    35 e-tron S line/Matrix/Pano/ACC/SONOS/LM 21  
3           2.0 Lifestyle Plus Automatik Navi FAP  
4                    1.6 T 48V 2WD Spirit LED, WR

In [32]:
# last five rows
df.tail(5)

Unnamed: 0       brand                 model  color registration_date  \
99995        6265        audi               Audi A1   blue           05/2012   
99996       54886        fiat              Fiat 500  black           12/2019   
99997       76820       honda            Honda CR-V  brown           01/2019   
99998         860  alfa-romeo  Alfa Romeo Giulietta   grey           12/2020   
99999       15795        audi               Audi A3  black           05/2018   

       year price_in_euro power_kw power_ps transmission_type fuel_type  \
99995  2012         12599       90      122            Manual    Petrol   
99996  2019          9999       51       69         Automatic    Petrol   
99997  2019         24800      127      173            Manual    Petrol   
99998  2020         22990      125      170         Automatic    Diesel   
99999  2018         21900      110      150            Manual    Petrol   

      fuel_consumption_l_100km fuel_consumption_g_km  mileage_in_km  \
99995             5,3 l/100 km              126 g/km       148000.0   
99996             5,2 l/100 km              120 g/km        31698.0   
99997             6,3 l/100 km              143 g/km        77900.0   
99998             5,5 l/100 km              145 g/km        52251.0   
99999             5,3 l/100 km              120 g/km        30400.0   

                                      offer_description  
99995        Ambition TFSI Navi/Leder/SHZ/PTS/KETTE NEU  
99996                       1.2 Lounge +Automatik + PDC  
99997  1.5T 2WD Elegance * 1. Hand * 24 Mon. Garantie *  
99998            Lusso Ti 2.0 JTDM 16V Xenon Leder Navi  
99999         Sportback1.5 Sport|VIRTUAL|NAVI|LED|30KM|

In [33]:
# Find out the measures of central tendancy for this Numpy array : np.array([1,5,5,3,100,4,48])

In [36]:
import numpy as np
n1 =np.array([1,5,5,3,100,4,48])

print("The mean is:",(np.mean(n1)))
print("The median is:",(np.median(n1)))
print("The std is:",(np.std(n1)))

The mean is: 23.714285714285715
The median is: 5.0
The std is: 34.73044891205198


In [37]:
# How do you get lis of all keys in the dict
dict = {"first_name":"John","Middle_name":"Suresh","last_name":"Mahire"}

In [38]:
dict.keys()

dict_keys(['first_name', 'Middle_name', 'last_name'])

In [39]:
str = "greatlearning"

In [40]:
print(str.capitalize())


Greatlearning


In [41]:
# how can u insert element in  in given index


In [44]:
list = [1,2,3,4,56,7,8,9,9]
list.insert(0,3)

list

[3, 1, 2, 3, 4, 56, 7, 8, 9, 9]

In [46]:
# how will iu delete duplicate elements from list 


In [52]:
m = ['x','y','z','x','y','z','a','b','c','d']

my_list = list(dict.fromkeys(m))
print(my_list)

['x', 'y', 'z', 'a', 'b', 'c', 'd']


In [53]:
# explain python list comprehension

list = [i for i in range(10)]

list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
# map function

def add_func(n):
    return n*2

num = (1,2,3,4)
result = map(add_func,num)

print(list(result))

[2, 4, 6, 8]


In [57]:
# how to convert int type into str 

In [74]:
num = 10
del str # if type error comes do this del str ,del list etc 

print(type(num))

char = str(num)

print(type(char))

<class 'int'>
<class 'str'>


In [83]:
letters = ("'A','B','C', 'helllo'")
n = letters.split(" ")  # it seperated string by space( )
print(n)

["'A','B','C',", "'helllo'"]
