In [1]:
import numpy as np

In [2]:
# 1 Create one dimentional an array

In [3]:
a = np.array([1,32,3,4,5,6])

In [4]:
a

array([ 1, 32,  3,  4,  5,  6])

In [5]:
# 2 create two dimentional an array

In [10]:
b = np.array([(1,2,3),(4,5,6)]) 

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 3 find the dimentions of an array

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b.ndim

2

In [26]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [27]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
c.ndim

2

In [14]:
# 4 find byte size of an  array

In [29]:
b.itemsize

4

In [15]:
# 5 find data type of an  array

In [30]:
b.dtype

dtype('int32')

In [16]:
# 6 find shape of  an array

In [31]:
b.size

6

In [32]:
b.shape

(2, 3)

In [17]:
# 7 reshape of  an array

In [33]:
d = np.array([(1,2,3,4),(5,6,7,8)])

In [34]:
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
d.shape

(2, 4)

In [37]:
d.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
# 8 slicing of an array

In [38]:
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
d[0:,0]   # it will fetch both zeroth index values

array([1, 5])

In [40]:
d[0:,1]

array([2, 6])

In [41]:
d[0:,2]

array([3, 7])

In [42]:
d[1:,1]   # if we have to fetch first index value from 2nd row

array([6])

In [43]:
d[0:1]   # if have to fetch only first row from array

array([[1, 2, 3, 4]])

In [44]:
d[1:2]  # if have to fetch only second row from array

array([[5, 6, 7, 8]])

In [45]:
d[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# 9 find min, max, mean, median, std of an array

In [47]:
d.max(),d.min(),d.mean(),d.std()

(8, 1, 4.5, 2.29128784747792)

In [21]:
# 10 axis

In [48]:
# axis 0 refers to column 
# axis 1 refers to row

In [49]:
d.sum(axis=0)

array([ 6,  8, 10, 12])

In [50]:
d.sum(axis=1)

array([10, 26])

In [22]:
# 11 concatenate array

In [52]:
x = np.array([(1,2,3,4,9),(5,6,7,8,9)])
y = np.array([(9,8,7,6,5),(5,4,3,2,1)])

In [53]:
np.vstack((x,y))

array([[1, 2, 3, 4, 9],
       [5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5],
       [5, 4, 3, 2, 1]])

In [54]:
np.hstack((x,y))

array([[1, 2, 3, 4, 9, 9, 8, 7, 6, 5],
       [5, 6, 7, 8, 9, 5, 4, 3, 2, 1]])

In [ ]:
# 12 convert multidimentional array into single column

In [55]:
np.ravel(x)

array([1, 2, 3, 4, 9, 5, 6, 7, 8, 9])

In [ ]:
# 13 Arithmatic operations on array

In [56]:
x = np.array([(1,2,3,4,9),(5,6,7,8,9)])
y = np.array([(9,8,7,6,5),(5,4,3,2,1)])

In [58]:
x+y

array([[10, 10, 10, 10, 14],
       [10, 10, 10, 10, 10]])

In [59]:
x-y

array([[-8, -6, -4, -2,  4],
       [ 0,  2,  4,  6,  8]])

In [60]:
x*y

array([[ 9, 16, 21, 24, 45],
       [25, 24, 21, 16,  9]])

In [61]:
x/y

array([[0.11111111, 0.25      , 0.42857143, 0.66666667, 1.8       ],
       [1.        , 1.5       , 2.33333333, 4.        , 9.        ]])